name: Test LeetCode Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run LeetCode Sync Action
        uses: ./
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrftoken: ${{ secrets.LEETCODE_CSRFTOKEN }}
          verbose: true